services:
  l402-example-app:
    build:
      context: .
      dockerfile: l402-example-app/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      L402_ENABLED: "true"
      L402_TEST_MODE: "true"
      L402_SERVICE_NAME: "example-api"
      L402_ROOT_KEY_STORE: "memory"
