services:
  paygate-example-app:
    build:
      context: .
      dockerfile: paygate-example-app/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      PAYGATE_ENABLED: "true"
      PAYGATE_TEST_MODE: "true"
      PAYGATE_SERVICE_NAME: "example-api"
      PAYGATE_ROOT_KEY_STORE: "memory"
